# Generated by Django 5.0.6 on 2024-06-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livraria", "0004_livro_autores"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
